version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./forum.db:/forum.db
      - type: bind
        source: ./server/frontend
        target: /app/server/frontend